<a href="https://colab.research.google.com/github/BAOTIN2004/Python_HUET/blob/main/bai10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
from numpy import random
from math import sin,cos,log,sqrt
x=random.randint(1,10,size=(1,5))

def bai1(x):
    print(np.round(np.sin(x),2))
    print(np.round(np.cos(x),2))
    print(np.round(np.sqrt(x),2))
    print(np.round(np.log(x),2))
    y=random.randint(1,10,size=(3,5))
    print(np.round(np.cos(y),3))
    print(np.round(np.sin(y),3))
    print(np.round(np.tan(y),3))
    print(np.round(np.sqrt(y),3))    
    print(np.round(np.log(y),3))
    
def bai2(x):
    print(np.linspace(-100,100,1000))
    f=3*x**2-2*x-4
    print(cos(f))
    print(sin(f))
    
def main():
    bai1(x)
    bai2(2)
if __name__=="__main__":
    main()


[[ 0.14 -0.96 -0.96  0.66  0.14]]
[[-0.99  0.28  0.28  0.75 -0.99]]
[[1.73 2.24 2.24 2.65 1.73]]
[[1.1  1.61 1.61 1.95 1.1 ]]
[[-0.654 -0.654  0.754 -0.99  -0.99 ]
 [-0.416 -0.99   0.54   0.96  -0.146]
 [ 0.754 -0.99  -0.99   0.284  0.754]]
[[-0.757 -0.757  0.657  0.141  0.141]
 [ 0.909  0.141  0.841 -0.279  0.989]
 [ 0.657  0.141  0.141 -0.959  0.657]]
[[ 1.158  1.158  0.871 -0.143 -0.143]
 [-2.185 -0.143  1.557 -0.291 -6.8  ]
 [ 0.871 -0.143 -0.143 -3.381  0.871]]
[[2.    2.    2.646 1.732 1.732]
 [1.414 1.732 1.    2.449 2.828]
 [2.646 1.732 1.732 2.236 2.646]]
[[1.386 1.386 1.946 1.099 1.099]
 [0.693 1.099 0.    1.792 2.079]
 [1.946 1.099 1.099 1.609 1.946]]
[-100.          -99.7997998   -99.5995996   -99.3993994   -99.1991992
  -98.998999    -98.7987988   -98.5985986   -98.3983984   -98.1981982
  -97.997998    -97.7977978   -97.5975976   -97.3973974   -97.1971972
  -96.996997    -96.7967968   -96.5965966   -96.3963964   -96.1961962
  -95.995996    -95.7957958   -95.5955956   -95.3