<a href="https://colab.research.google.com/github/BAOTIN2004/Python_HUET/blob/main/thuviennumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [16]:
v1=np.arange(-9,6,dtype=int)
print(v1)

[-9 -8 -7 -6 -5 -4 -3 -2 -1  0  1  2  3  4  5]


In [15]:
v1=np.linspace(1,10,20)
print(v1)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [20]:
from numpy import random
v=np.random.randint(2,10,8)
print(v)

[9 5 5 4 2 3 6 2]


In [21]:
v=np.random.uniform(-10,10,10)
print(v)

[-5.62741456  2.84845147 -0.61832818  3.37670811 -9.83014346 -2.54806194
  0.54348099 -2.93015979 -2.88610857 -7.66837379]


In [28]:
n=abs(int(input('Nhập n')))
print(np.arange(3,3+n,dtype=int ))
print(np.arange(2.7,2+n,dtype=float))
print(np.random.randint(-9,10,n))
print(np.random.uniform(-9,10,n))

Nhập n6
[3 4 5 6 7 8]
[2.7 3.7 4.7 5.7 6.7 7.7]
[-8 -6  4  0  8  4]
[ 3.98921183 -3.78787834 -4.33246959 -3.41472637  1.84722826  4.32286865]


In [33]:
v1=np.random.randint(-10,10,20)
print(v1.shape)
print(v1.ndim)

(20,)
1


In [35]:
v=np.random.randint(-10,10,10)
a=int(input('Nhap a '))
print(a*v)

Nhap a 9
[-81 -63   0   0  -9 -18 -81 -72  72  -9]


In [36]:
v=np.random.randint(-10,10,10)
l=np.random.randint(-10,10,10)
print(l+v)

[ -4  -6  16  -6  -4 -11  -5 -11  -1   0]


In [38]:
v=np.random.randint(-10,10,10)
l=np.random.randint(-10,10,10)
print(np.dot(v,l))

126


In [39]:
v=np.random.randint(-10,10,10)
l=np.random.randint(-10,10,10)
print(np.multiply(v,l))

[-16   4  18  15  35   6   0   0  90 -10]
